"""Camera capture, restore, sync, orbit, zoom, reset, and fit helpers."""

from __future__ import annotations

from ._graph_viewer_impl import (
    _active_scene_center_and_radius,
    _box_corners,
    _camera_bool,
    _camera_scalar,
    _camera_tuple,
    _capture_camera_state,
    _normalized,
    _refresh_after_camera_navigation,
    _reset_camera_clipping_range,
    _restore_camera_state,
    _rotate_vector,
    _scene_bounds,
    _set_camera_bool,
    _set_camera_scalar,
    _set_camera_tuple,
    _store_initial_camera_state,
    _store_shared_camera_state,
    _sync_camera_to_other_views,
    _zoom_active_camera,
    fit_active_preview,
    reset_active_view,
)

__all__ = [
    "_active_scene_center_and_radius",
    "_box_corners",
    "_camera_bool",
    "_camera_scalar",
    "_camera_tuple",
    "_capture_camera_state",
    "_normalized",
    "_refresh_after_camera_navigation",
    "_reset_camera_clipping_range",
    "_restore_camera_state",
    "_rotate_vector",
    "_scene_bounds",
    "_set_camera_bool",
    "_set_camera_scalar",
    "_set_camera_tuple",
    "_store_initial_camera_state",
    "_store_shared_camera_state",
    "_sync_camera_to_other_views",
    "_zoom_active_camera",
    "fit_active_preview",
    "reset_active_view",
]
