"""Renderer layout, overlay drawing, headers, and file-panel helpers."""

from __future__ import annotations

from ._graph_viewer_impl import (
    _add_actor2d,
    _add_file_panel_row,
    _add_overlay_rect,
    _add_overlay_text,
    _axes_marker_viewport,
    _draw_header_cell,
    _ensure_overlay_renderer,
    _overlay_color,
    _plotter_window_size,
    _remove_actor_list,
    _render_double_view_headers,
    _render_overlay_header,
    _scene_area_fraction,
    _scene_column,
    _scene_renderer,
    _select_view_renderer,
    _set_axes_marker_visible,
    _set_error,
    _set_status,
    _text_actor_property,
    _tools_panel_width,
    apply_view_layout,
    render_file_panel,
    render_view_headers,
)

__all__ = [
    "_add_actor2d",
    "_add_file_panel_row",
    "_add_overlay_rect",
    "_add_overlay_text",
    "_axes_marker_viewport",
    "_draw_header_cell",
    "_ensure_overlay_renderer",
    "_overlay_color",
    "_plotter_window_size",
    "_remove_actor_list",
    "_render_double_view_headers",
    "_render_overlay_header",
    "_scene_area_fraction",
    "_scene_column",
    "_scene_renderer",
    "_select_view_renderer",
    "_set_axes_marker_visible",
    "_set_error",
    "_set_status",
    "_text_actor_property",
    "_tools_panel_width",
    "apply_view_layout",
    "render_file_panel",
    "render_view_headers",
]
